### ISSUE TITLE
link to download pre-compiled serialized machine graphs not working

### ISSUE THREAD

**Issue by crystal-butler** [kornai/4lang#164]
The README link to download pre-compiled serialized machine graphs is not resolving for me: http://sandbox.hlt.bme.hu/~recski/4lang/machines.tgz 
Is this file still available?

**Comment by recski** [comment]
Yes, thanks for reporting, we have some temporary issues with the server,
I'll post an alternative link if it isn't resolved by tomorrow.

Crystal Butler <notifications@github.com> schrieb am So., 12. Juli 2020,
22:05:

**Comment by recski** [comment]
The resource is back online, thanks again!
