### ISSUE TITLE
IN IN IN IN IN IN IN ...

### ISSUE THREAD

**Issue by DavidNemeskey** [kornai/4lang#63]
http://people.mokk.bme.hu/~recski/4lang_graphs/eksz_firsts_160211/a/a1bra1zol.jpg

**Comment by kornai** [comment]
WTF?

**Comment by recski** [comment]
nyilván bug, majd ránézek jövőhéten, most semeval cikket kell írnom...

**Comment by gaebor** [comment]
@DavidNemeskey le tudod írni kicsit részletesebben hogy hogyan lehet reprodukálni?
Akkor rá tudok nézni én is.

**Comment by DavidNemeskey** [comment]
@gaebor Hát én azt honnan tudjam? A linket sem ismertem, csak a Kálmán wikijéről találtam meg...

**Comment by recski** [comment]
hát ez nem a jövőhét volt, sorry
