### ISSUE TITLE
Plurals in 4lang

### ISSUE THREAD

**Issue by DavidNemeskey** [kornai/4lang#86]
Why are there plurals in 4lang? To make it more difficult to process automatically? :)

Examples: cars, lessons, shapes, sides, sleeves, weapons, winds, words.

**Comment by makrai** [comment]
Thanks for noting. Once I fixed many of this, but it seems that I fixed at most one plural in a definition. Now I go on.

**Comment by makrai** [comment]
@DavidNemeskey I don't find winds. Did you mistype it?

**Comment by DavidNemeskey** [comment]
@makrai yes, I meant "wings". But I suggest you just search for `s `, so that you don't miss those I have.

**Comment by makrai** [comment]
solved by https://github.com/kornai/4lang/issues/89
